export const ALL_PRODUCT_REQUEST = 'ALL_PROODUCT_REQUEST';
export const ALL_PRODUCT_SUCCESS = 'ALL_PROODUCT_SUCCESS';
export const ALL_PRODUCT_FAIL = 'ALL_PROODUCT_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PROODUC_DETAILST_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PROODUC_DETAILST_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PROODUC_DETAILST_FAIL';

export const PRODUCT_UPDATE_REQUEST = 'PROODUC_UPDATET_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PROODUC_UPDATET_SUCCESS';
export const PRODUCT_UPDATE_RESET = 'PROODUC_UPDATET_RESET';
export const PRODUCT_UPDATE_FAIL = 'PROODUC_UPDATET_FAIL';

export const CREATE_PRODUCT_REQUEST = 'CREATE_PROODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PROODUCT_SUCCESS';
export const CREATE_PRODUCT_FAIL = 'CREATE_PROODUCT_FAIL';
export const CREATE_PRODUCT_RESET = 'CREATE_PROODUCT_RESET';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
